stages:
  - test
  - docker
  
jobs:
  include:
    # Run tests for the Python code
    - language: python
      python: 3.8
      script:
        - python -m unittest python_runner/tests/runner_test.py
      after_success:

    # Run tests for Groovy
    - language: groovy
      before_script:
        - ./gradlew assemble
      script:
        - ./gradlew test
      after_success:

    # Generate docker images (only if modified)
    - stage: docker conanio/conantests
      env: 
        - IMAGE=conan_tests
        - LINTER=false

language: minimal
before_install:
  - |
    count=`git diff --name-only $TRAVIS_COMMIT_RANGE | sort -u | uniq | grep docker_images | wc -l`
    if [ $count -ne 0 ]
    then
      echo "Build docker images"
    else
      echo "No docker image to build"
      travis_terminate 0
    fi
script:
  - echo "Building docker image 'conanio/$IMAGE'"
  - if [[ "$LINTER" != "false"]] docker run --rm -i hadolint/hadolint < docker_images/$IMAGE/Dockerfile
  - docker build -t travis-ci-$IMAGE docker_images/$IMAGE
  - docker images
  - docker tag travis-ci-$IMAGE conanio/$IMAGE

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" and "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
      echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin;
      docker push conanio/$IMAGE;
    fi