stages:
  - test
  - docker
  
jobs:
  include:
    # Run tests for the Python code
    - name: Run Python tests
      language: python
      python: 3.8
      before_install:
      script:
        - cd resources/org/jfrog/conanci
        - python -m unittest python_runner/tests/runner_test.py
      after_success:

    # Run tests for Groovy
    - name: Run Groovy tests
      language: groovy
      before_install:
      before_script:
        - ./gradlew assemble
      script:
        - ./gradlew test
      after_success:

    # Generate docker images (only if modified)
    #- stage: docker conanio/conantests
    #  env: 
    #    - IMAGE=conan_tests
    #    - LINTER=false
    - stage: docker
      name: conanio/ci-unittests
      env: 
        - IMAGE=ci-unittests
    - name: conanio/ci-functional
      env: 
       - IMAGE=ci-functional
       - IMAGE_ARGS="gcc 12 clang 12 cmake 12"  # Non valid values
    
      
language: minimal
before_install:
  - |
    count=`git diff --name-only $TRAVIS_COMMIT_RANGE | sort -u | uniq | grep docker_images | wc -l`
    if [ $count -ne 0 ]
    then
      echo "Build docker images"
    else
      echo "No docker image to build"
      travis_terminate 0
    fi
script:
  - echo "Building docker image 'conanio/$IMAGE'"
  - |
    if [[ "$LINTER" != "false" ]]
    then
      docker run --rm -i hadolint/hadolint < docker_images/$IMAGE/Dockerfile || true;
    fi
  - docker build -t travis-ci-$IMAGE docker_images/$IMAGE
  - docker images
  - docker tag travis-ci-$IMAGE conanio/$IMAGE
  # Run tests outside the docker image
  - . $(pwd)/docker_images/_tests/run_outside_tests.sh
  # Run some tests inside the image
  - docker run -v "$(pwd)/docker_images/_tests:/home/tests" --env IMAGE=$IMAGE conanio/$IMAGE $IMAGE_ARGS -c "export PYTHON=\$PY38 && /home/tests/run_tests.sh"

after_success:
  - |
    if [[ "$TRAVIS_BRANCH" == "master" && "${TRAVIS_PULL_REQUEST}" == "false" ]]
    then
      echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin;
      docker push conanio/$IMAGE;
    fi