stages:
  - test
  - docker

language:
  - python
  - groovy
python:
  - 3.7
  - 3.8

jobs:
  include:
    - language: python
      script:
        - python -m unittest python_runner/tests/runner_test.py

    - language: groovy
      before_script:
        - ./gradlew assemble
      script:
        - ./gradlew test

    # Generate docker images (only if modified)
    - stage: docker
      env: IMAGE=Base
    - env: IMAGE=MULTI

language: minimal
before_install:
  - |
    count=`git diff --name-only $TRAVIS_COMMIT_RANGE | sort -u | uniq | grep docker_images | wc -l`
    if [ $count -ne 0 ]
    then
      echo "Build docker images"
    else
      echo "No docker image to build"
      travis_terminate 0
    fi
script:
  - echo "Building docker image $IMAGE"
  - docker build --help