matrix:
  include:
    - language: python
      python: 3.7
      script:
        - python -m unittest python_runner/tests/runner_test.py

    - language: python
      python: 3.8
      script:
        - python -m unittest python_runner/tests/runner_test.py

    - language: groovy
      before_script:
        - ./gradlew assemble
      script:
        - ./gradlew test

