/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package org.jfrog.conanci


import spock.lang.Specification

class SomeTest extends Specification {

    def "I could add some tests here"(){
        given:
            int left = 2
            int right = 2

        when:
            int result = left + right

        then:
            result == 4
    }

}
