/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package org.jfrog.conanci


import spock.lang.Specification

class SomeTest extends Specification {



    def "I could add some tests here"(){

    }

}
