node("Linux") {
    stage("Checkout the sources") {
        checkout scm
    }
    // stage("Test") {
    //     docker.image("gradle:6.7.0").inside() {
    //         sh(script: "apt-get update && apt-get install -y python3 python3-pip")
    //         stage("Python tests") {
    //             sh(script: "cd resources/org/jfrog/conanci && python3 -m unittest python_runner/tests/runner_test.py")
    //         }
    //         stage("Groovy tests") {
    //             sh(script: "./gradlew assemble && ./gradlew test")
    //         }
    //     }
    // }
    stage("Check if conantests image has to be built") {
        def target_branch = (env.BRANCH_NAME.startsWith('PR')) ? "${env.CHANGE_TARGET}" : "${env.BRANCH_NAME}"
        def current_commit = sh(script: "git rev-parse HEAD", returnStdout: true).trim()
        sh(script: "git checkout ${target_branch}")
        def previous_commit = sh(script: "git rev-parse HEAD", returnStdout: true).trim()
        sh(script: "git checkout ${current_commit}")
        def count = sh(script: "git diff --name-only ${previous_commit}..${current_commit} | sort -u | uniq | grep docker_images | wc -l", returnStdout: true).trim()
        echo "${count}"
    }
}